[tox]
envlist = membership-begin,membership-py{36,37,39,310}-{PySide2,PyQt5},membership-py{310,311}-{PySide6,PyQt6},membership-end
; envlist = py{36,37,39,310}-{PySide2,PyQt5},py{310,311}-{PySide6,PyQt6}
skip_missing_interpreters = True

# To support testing py3.6 we have to use a older virtualenv
; requires =
;     virtualenv<=20.0

[testenv]
# These are used by all other testenv definitions unless overridden
changedir = {toxinidir}
pass_env =
    QT_VERBOSE

[testenv:membership-begin]
# Cleanup any files left over from other membership tests that may have been run
skip_install = True
commands =
    python membership.py --clean

[testenv:membership-py{36,37,39,310,311}-{PySide2,PyQt5,PySide6,PyQt6}]
# Generate the binding .json files for each requirement
depends = membership-begin
# This test is not using Qt.py, so prevent tox from trying to install it.
# This works around install issues with setuptools in py3.7.
skip_install = True
setenv =
    TOX_NAME = {envname}
    py{36,37}: VIRTUALENV_PIP==24.0
    py{36,37,39,310}-PySide2: binding = PySide2
    py{36,37,39,310}-PyQt5: binding = PyQt5
    py{310,311}-PySide6: binding = PySide6
    py{310,311}-PyQt6: binding = PyQt6
deps =
    # Using the oldest Qt5 versions available for Py 3.7 for reporting
    py{36,37}-PySide2: PySide2==5.11.2
    py{36,37}-PyQt5: PyQt5==5.8.2
    # VFX Reference Platform CY2022/CY2023
    py{39,310}-PySide2: PySide2==5.15.*
    py{39,310}-PyQt5: PyQt5==5.15.*
    # VFX Reference Platform CY2024 + py3.10
    py{310,311}-PySide6: PySide6==6.5.*
    py{310,311}-PyQt6: PyQt6==6.5.*;platform_system=="Linux"
    # 6.5 raises `The specified procedure could not be found.` errors on windows
    py{310,311}-PyQt6: PyQt6==6.7.*;platform_system=="Windows"
commands =
    python -c 'print("{env:binding}")'
    python membership.py --binding {env:binding}

[testenv:membership-end]
# Combine the binding.json files into the common members .json files
skip_install = True
depends = membership-py{36,37,39,310,311}-{PySide2,PyQt5,PySide6,PyQt6}
deps =
    tabulate
commands =
    # Generate common_members.json
    python membership.py --generate-common-members

[testenv:py{36,37,39,310,311}-{PySide2,PyQt5,PySide6,PyQt6}]
# Run nose tests for each requirement
setenv =
    QT_VERBOSE=1
    py{36,37,39,310}-PySide2: QT_PREFERRED_BINDING = PySide2
    py{36,37,39,310}-PyQt5: QT_PREFERRED_BINDING = PyQt5
    py{310,311}-PySide6: QT_PREFERRED_BINDING = PySide6
    py{310,311}-PyQt6: QT_PREFERRED_BINDING = PyQt6
deps =
    py{36,37,39,310}: PySide2==5.15.*
    py{36,37,39,310}: PyQt5==5.15.*
    py{310,311}: PySide6==6.5.*
    py{310,311}: PyQt6==6.5.*;platform_system=="Linux"
    # 6.5 raises `The specified procedure could not be found.` errors on windows
    py{310,311}: PyQt6==6.7.*;platform_system=="Windows"
    nose2
    nosepipe
    six
commands =
    python -m nose2 --verbose tests