[tox]
envlist =
    # `membership-` testenv's generate binding membership information
    # Clean up files from previous test runs
    membership-begin
    # Enable these to inspect older VFX Platform requirements
    ; membership-20{20,21,22}-{PySide2,PyQt5}
    ; membership-2024-{PySide6,PyQt6}

    # The latest Qt5 VFX platform requirement
    membership-2023-{PySide2,PyQt5}
    membership-2025-{PySide6,PyQt6}
    # Generate common members from the previous tests generated files
    membership-end

    # `test-` testenvs run the nose tests to test Qt.py's code
    # Enable these to test older VFX Platform requirements
    ; test-20{20,22}-{PySide2,PyQt5}
    ; test-2024-{PySide6,PyQt6}

    # The latest Qt5 VFX platform requirement
    test-2021-{PySide2,PyQt5}
    test-2023-{PySide2,PyQt5}
    test-2023-{PySide6,PyQt6}
    test-2025-{PySide6,PyQt6}

skip_missing_interpreters = True

[testenv]
# These are used by all other testenv definitions unless overridden
changedir = {toxinidir}
pass_env =
    QT_VERBOSE
# For membership- tests we don't need Qt.py to be installed. This speeds up
# running the tests and works around install issues with setuptools in py3.7.
skip_install = True
basepython =
    20{20,21}: python3.7
    2022: python3.9
    2023: python3.10
    20{24,25}: python3.11

[testenv:membership-begin]
# Cleans up any files left over from previous membership tests runs
commands =
    python membership.py --clean

[testenv:membership-20{25,24,23,22,21,20}-{PySide2,PyQt5,PySide6,PyQt6}]
# Generate the binding .json files for each requirement
depends = membership-begin
setenv =
    PySide2: BINDING=PySide2
    PySide6: BINDING=PySide6
    PyQt5: BINDING=PyQt5
    PyQt6: BINDING=PyQt6
    # This is required for py37 to prevent syntax errors due to positional-only parameters
    20{20,21}: VIRTUALENV_PIP==24.0
deps =
    2020-PySide2: PySide2==5.12.*
    20{21,22,23}-PySide2: PySide2==5.15.*
    20{22,23}-PyQt5: PyQt5==5.15.*
    20{24,25}-PySide6: PySide6==6.5.*
    20{24,25}-PyQt6: PyQt6==6.5.*;platform_system=="Linux"
    # 6.5 raises `The specified procedure could not be found.` errors on windows
    20{24,25}-PyQt6: PyQt6==6.7.*;platform_system=="Windows"
commands =
    # Workaround for testing PyQt5 in python 3.7.
    # PyQt5-sip has sdists for "PyQt5-sip>12.12" but that is the last version that
    # still built wheels for python 3.7. This forces pip to only install from wheels
    # which keeps pip from trying to compile it on windows.
    20{20,21}-PyQt5: pip install --only-binary=:all: PyQt5==5.13.*

    # Build the membership for the requested Qt binding
    python membership.py --binding {env:BINDING}

[testenv:membership-end]
# Combine the .json files generated by previous tests into the common member files.
depends = membership-20{25,24,23,22,21,20}-{PySide2,PyQt5,PySide6,PyQt6}
commands =
    python membership.py --generate-common-members

[testenv:test-20{25,24,23,22,21,20}-{PySide2,PyQt5,PySide6,PyQt6}]
# Run nose tests for each requirement
# We need Qt.py to be installed for nose tests
skip_install = False
# Force tests to run after membership
depends = membership-end
pass_env =
    # This env var lets runners control what platform is used to create
    # QApplications. This lets headless linux runners use the vnc platform.
    QT_QPA_PLATFORM
setenv =
    QT_VERBOSE=1
    PySide2: QT_PREFERRED_BINDING=PySide2
    PySide6: QT_PREFERRED_BINDING=PySide6
    PyQt5: QT_PREFERRED_BINDING=PyQt5
    PyQt6: QT_PREFERRED_BINDING=PyQt6
    # These are required for py37 to prevent errors caused by newer versions
    20{20,21}: VIRTUALENV_PIP==24.0
    20{20,21}: VIRTUALENV_SETUPTOOLS==44.1.1
    20{20,21}: VIRTUALENV_WHEEL==0.42.0
deps =
    2020: PySide2==5.12.*
    20{21,22,23}: PySide2==5.15.*
    20{22,23,24}: PyQt5==5.15.*
    20{23,24,25}: PySide6==6.5.*
    20{23,24,25}: PyQt6==6.5.*;platform_system=="Linux"
    # 6.5 raises `The specified procedure could not be found.` errors on windows
    20{23,24,25}: PyQt6==6.7.*;platform_system=="Windows"
    nose2
    nosepipe
    six
    packaging
    setuptools
    wheel
commands =
    # Workaround for testing PyQt5 in python 3.7.
    # PyQt5-sip has sdists for "PyQt5-sip>12.12" but that is the last version that
    # still built wheels for python 3.7. This forces pip to only install from wheels
    # which keeps pip from trying to compile it on windows.
    20{20,21}: pip install --only-binary=:all: PyQt5==5.13.*

    # Run the nose tests
    python -m nose2 --verbose {posargs:tests}