# These docker based tests are being replaced by tox based testing. These tests
# focus on testing Python 2.7-3.5 and Qt4 and Qt5 testing. The run-tox.yml based
# tests focus on python 3.7+ and Qt5 and Qt6 testing.
#
# Once we drop Qt4 support these files should be removed from the repo:
#   .github/workflows/pyside6.yml
#   .github/workflows/run-tests.yml
#   DOCKER.md
#   Dockerfile.vfxplatform2017
#   Dockerfile.vfxplatform2018
#   build_docker.sh
#   build_membership.sh
#   entrypoint.sh
#   run_docker.sh
#   run_tests.py
#   test_docker.sh

name: Run Docker Tests(Pending Removal)

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            VFXPLATFORM: "2018"
            PYTHON: "2.7"
          - os: ubuntu-latest
            VFXPLATFORM: "2018"
            PYTHON: "3.4"
          - os: ubuntu-latest
            VFXPLATFORM: "2018"
            PYTHON: "3.5"
          - os: ubuntu-latest
            VFXPLATFORM: "2018"
            PYTHON: "3.6"
          - os: ubuntu-latest
            VFXPLATFORM: "2017"
            PYTHON: "2.7"
          - os: ubuntu-latest
            VFXPLATFORM: "2017"
            PYTHON: "3.4"
          - os: ubuntu-latest
            VFXPLATFORM: "2017"
            PYTHON: "3.5"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests in Docker container
        run: |
          docker run --rm \
            -v $(pwd):/Qt.py \
            -e PYTHON=${{ matrix.PYTHON }} \
            fredrikaverpil/qt.py:${{ matrix.VFXPLATFORM }}
